set1=([1,2,3,4])
set2=([3,4,5,6])
union_set=(set1)|(set2)
intersection_set=(set1) & (set2)
difference_set=(set1)-(set2)
print("Frozen 1:",set1)
print("Frozen 2:",set2)
print("print Union:",Union_set)
print("print intersection:",intersection_set)
print("print Difference:",difference_set)
