set_input = input("Enter elements of the set (separated by space or comma): ")
set_input = set(map(int, set_input.replace(",", " ").split()))
print("\nOriginal Set:", set_input)
tuple_from_set = tuple(set_input)
print("Converted Tuple:", tuple_from_set)
tuple_input = input("\nEnter elements of the tuple (separated by space or comma): ")
tuple_input = tuple(map(int, tuple_input.replace(",", " ").split()))
print("Original Tuple:", tuple_input)
set_from_tuple = set(tuple_input)
print("Converted Set:", set_from_tuple)
